// This file is AUTO GENERATED by CMake.
#pragma once
#include "SDL_video.h"

#ifdef NSPIRE
const static char* FILENAME_CONFIG = "./config.xml.tns";
const static char* FILENAME_SCORES = "./hiscores.tns";
const static char* FILENAME_TTRIAL = "./hiscores_timetrial.tns";
const static char* FILENAME_CONT   = "./hiscores_continuous.tns";
const static int SDL_FLAGS = SDL_SWSURFACE;
#endif

#if defined(GCW)
const static char* FILENAME_CONFIG = "/media/data/local/home/.cannonball/config.xml";
const static char* FILENAME_SCORES = "/media/data/local/home/.cannonball/hiscores";
const static char* FILENAME_TTRIAL = "/media/data/local/home/.cannonball/hiscores_timetrial";
const static char* FILENAME_CONT   = "/media/data/local/home/.cannonball/hiscores_continuous";
const static int SDL_FLAGS = SDL_HWSURFACE;
#endif

#if !defined(GCW) && !defined(NSPIRE)
const static char* FILENAME_CONFIG = "./config.xml";
const static char* FILENAME_SCORES = "./hiscores";
const static char* FILENAME_TTRIAL = "./hiscores_timetrial";
const static char* FILENAME_CONT   = "./hiscores_continuous";
const static int SDL_FLAGS = SDL_SWSURFACE | SDL_DOUBLEBUF;
#endif

    
