// This file is AUTO GENERATED by CMake.
#pragma once
#include "SDL_video.h"

extern char FILENAME_CONFIG[256];
extern char FILENAME_SCORES[256];
extern char FILENAME_TTRIAL[256];
extern char FILENAME_CONT[256];
/*
const static char* FILENAME_CONFIG = "config.xml";
char* FILENAME_SCORES = "hiscores";
char* FILENAME_TTRIAL = "hiscores_timetrial";
char* FILENAME_CONT   = "hiscores_continuous";*/
const static int SDL_FLAGS = SDL_SWSURFACE;
